# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

name: Flatpak

on:
  workflow_dispatch:

jobs:
  flatpak:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Flatpak
        run: sudo apt install -y flatpak flatpak-builder

      - name: Add Flathub repository
        run: flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build
        run: flatpak-builder build --force-clean --user --install-deps-from=flathub --repo repo --install .flatpak-manifest.json

      - name: Create package
        run: flatpak build-bundle repo chessament.flatpak dev.alcarazzam.chessament --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chessament.flatpak
          path: chessament.flatpak
          if-no-files-found: error

